/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import code.WordChecker;
import java.util.Map.Entry;
import javax.swing.JOptionPane;

/**
 *
 * @author castuardo
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter a word");

        jButton1.setText("Check word");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // This is where the code goes for this button
        // We are going to do several thing with the word, but first we
        // need to get it
        String text = jTextField1.getText();
        // is the something here?
        if(text != null && text.length() > 0){
            // This is the class that knows what to do with the word.
            // Its always good to separate especific concerns and code
            // in different files. That makes it easier to look for it
            // in the future
            WordChecker check = new WordChecker();
            // lets reverse
            String reversed = check.reverseWord(text);
            
            // Now, lets write the result to the screen. Ill use
            // the big text field (its called text area). Ill clean it first.
            jTextArea1.setText(null);
            jTextArea1.append("You entered the word " + text + "\n"); // \n is to insert a new line,
            // cause i want each line separated. Remove it an see what happens
            jTextArea1.append("The reversed word is " + reversed + "\n");
            // a palindrome is a word that when reversed looks just like the original,
            // like rotator. This operator: z = (x == y)? a : b assigns a to z if x == y is true
            // and b if false.
            jTextArea1.append("This word is" + ((check.isPalindrome(text))? " " : " not ") + "a palindrome\n");
            // and now, we count letters and show
            jTextArea1.append("This word has:\n");
            // This is how you iterate through a map. 
            for(Entry<Character, Integer> letterKeyValue : check.countLetters(text).entrySet()){
                // letterKeyValue is a pair. The key is a char and the value an int
                jTextArea1.append("   " + letterKeyValue.getValue() + " " + letterKeyValue.getKey() + "'s\n");
            }
        }
        else{
            // empty word, error
             JOptionPane.showMessageDialog(
                this,// this is because the small message window belong to the main window
                "You need to enter a word!",// this is the title
                "There was an unexpected problem...",// this is the message
                JOptionPane.ERROR_MESSAGE);// the error icon is added because of this
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
